### ISSUE TITLE
Fix startup connection bug

### ISSUE THREAD

**Issue by Neshri** [Steinstark/Camera#5]
The program gets stuck if one of the connections fails (changing the target port) from start.

**Comment by Steinstark** [comment]
Kan du fortfarande återskapa problemet (med senaste versionen)?

**Comment by Neshri** [comment]
Nej, men istället går det inte att ansluta efter att ha misslyckats första gången, det går alltså inte ändra target-porten efter att man tryckt på connect

**Comment by Steinstark** [comment]
Ändrade ett litet fel. Om jag förstått dig rätt så ska det vara fixat. Jag kan inte reproducerat i nuläget iallafall.

**Comment by Neshri** [comment]
Varför går det inte att köra i synkroniserat läge nu?

**Comment by Steinstark** [comment]
För att jag gjorde en ganska stor förändring i hur hela systemet kommunicerar igår och har inte hunnit porta om alla bitar av programmet för att använda det nya systemet. Tog bort all kommunikation och såg till att den går via monitorn istället.
